apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: vote-deployment
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app: redis-deployment