apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
  labels:
    app: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
      - name: redis-deployment
        image: redis:alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}