apiVersion: v1
kind: Pod
metadata:
  name: jekyll
  labels:
        run: jekyll
spec:
  containers:
  - name: jekyll
    image: kodekloud/jekyll-serve
    ports:
    - containerPort: 80
    volumeMounts:
        - name: site
          mountPath: /site
  initContainers:
  - name: copy-jekyll-site
    image: kodekloud/jekyll
    command: [ "jekyll", "new", "/site" ]
    volumeMounts:
        - name: site
          mountPath: /site
  volumes:
    - name: site
      persistentVolumeClaim:
        claimName: jekyll-site