apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jekyll-site
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      app: jekyll-site